require("dotenv").config();
const express = require("express");
const app = express();
const bodyParser = require("body-parser");
const { router } = require("./routes/routes");
const cookieParser = require("cookie-parser");
app.use(bodyParser.urlencoded({ $extended: true }));
app.use(express.json());
app.use(cookieParser(process.env.COOKIE_SECRET));
const mongoose = require("mongoose");
app.use(router);
mongoose.connect(process.env.MONGO_URI);
app.listen(5000);
